env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
overrides: []
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
rules: { "import/order": ["error", { alphabetize: { order: "asc" } }] }
settings:
  react:
    version: detect
