require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - standard

inherit_gem:
  standard: config/base.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - Rakefile
    - config.ru
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/assets.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/inflections.rb
    - config/initializers/permissions_policy.rb
    - config/puma.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

RSpec/ContextWording:
  AllowedPatterns:
    - とき$

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
